### ISSUE TITLE
[Bug][Scheduler] Using vertical grouping with a custom edit form prevents the form from opening

### ISSUE THREAD

**Issue by filipKovachev** [telerik/kendo-vue#531] opened 2024-02-29 10:50 UTC
**Describe the bug**
When we have a custom edit form and vertical grouping, we cannot open the form to edit the event
**To Reproduce**
1. Open this StackBlitz: https://stackblitz.com/edit/epkct9-bh1j1y?file=src%2Fmain.vue
2. Try to open the form on an event and notice you can't. If you set the grouping to horizontal then it works

**Expected behavior**
The custom form should open with grouping set to vertical as well.

Ticket ID: 1640687

**Comment by zdravkov** [comment] 2024-03-06 12:44
The issue is fixed in the dev npm version - https://stackblitz.com/edit/epkct9-y5uxg8 - will be available in the next official version of Kendo UI for Vue.

**Closed by zdravkov** 2024-03-06 12:44 UTC
Labels: Bug, SEV: Medium, Kendo UI for Vue
