### ISSUE TITLE
[Bug][DateRangePicker] Start and end dates can't be set through the inputs (with the keyboard)

### ISSUE THREAD

**Issue by kdikov82** [telerik/kendo-vue#460] opened 2023-09-26 18:24 UTC
It is not possible to set start nor end dates in the DateRangePicker with the keyboard within the input elements:

- https://stackblitz.com/edit/lcxavj?file=src%2Fmain.vue

Even if the range is set through the popup, changing the start date in the input will set some strange values in the "end" input.

**Comment by zdravkov** [comment] 2024-02-21 07:02
The issue is fixed in v4.3.1 of Kendo UI for Vue: https://stackblitz.com/edit/lcxavj-1n1ou2?file=src%2Fmain.vue

**Closed by zdravkov** 2024-02-21 07:02 UTC
Labels: Bug, SEV: Blocking, Kendo UI for Vue
