### ISSUE TITLE
Kendo UI Native Vue Editor - can't edit value

### ISSUE THREAD

**Issue by SBACer** [telerik/kendo-vue#329] opened 2022-11-17 16:02 UTC
I tried replacing the wrapper component with a native component. This caused me difficulties, I updated my component according to the documentation, but the value inside the editor does not change as I enter, although I can network it through setHtml. I created sandbox with this problem https://github.com/SBACer/vue-2-kendo-editor

**Comment by zdravkov** [comment] 2022-11-21 10:27
Thank you for reporting the issue!
It seems like it is caused by some issue with the content-styles property and when we define it as in the code below the editor is working correctly :
:content-style="{ ...editorStyles }"

Here is a example of the workaround that worked correctly at my side - https://codesandbox.io/s/determined-elbakyan-3h074q?file=/src/App.vue

Please review it and let me know if you still observe the issue after you applied the workaround. Meanwhile I am marking the issue as bug.

**Comment by SBACer** [comment] 2022-11-22 13:52
Thank you, that's helped. When do you plan to fix it?

**Comment by zdravkov** [comment] 2022-11-22 14:06
Thank you for your feedback.
We will do our best to have it fixed at latest for our next official version update that is planned for the beginning of December.
Meanwhile if you have further questions or you observe other issues please don't hesitate to let us know again. In such cases we recommend creating an account and submitting a support ticket so that we could provide a better customer support - https://www.telerik.com/support/kendo-ui-for-vue.

**Comment by zdravkov** [comment] 2023-01-25 07:08
Fixed in v3.8.1 of Kendo UI for Vue - https://codesandbox.io/s/green-microservice-ryglpf

**Closed by zdravkov** 2023-01-25 07:08 UTC
Labels: bug
