### ISSUE TITLE
[Bug][DropDownTree] If there is no "label" set to the component, the "style" properties are not set to the wrapping element

### ISSUE THREAD

**Issue by kdikov82** [telerik/kendo-vue#590] opened 2024-06-27 10:15 UTC
**Describe the bug**
If the DropDownTree has set "label", it is possible to add styles (as width) to the wrapping element, but if there is no label, the "style" values are not set.

**To Reproduce**
[Steps to reproduce the behavior:](https://stackblitz.com/edit/ggklvo?file=src%2Fmain.vue)

**Expected behavior**
Both configuration from the example must have the same width

**Screenshots**

Version: 5.1.0

Workaround: wrap the DropDownTree in a DIV with the style property

**Comment by zdravkov** [comment] 2024-07-15 08:07
The issue is fixed in the latest 'dev' version of Kendo UI for Vue and will be added to the next official release, too - https://stackblitz.com/edit/ggklvo-w9g9oh?file=package.json

**Closed by zdravkov** 2024-07-15 08:07 UTC
Labels: Bug, SEV: Medium, Kendo UI for Vue
