### ISSUE TITLE
DropDowns: The appendTo and className properties of the popup cannot be set through popupSettings

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-vue#222] opened 2022-03-18 09:58 UTC
**Describe the bug**
The **appendTo** and **className** properties of the Popup component cannot be set for the DropDowns, when configured through the [**popupSettngs** prop](https://www.telerik.com/kendo-vue-ui/components/dropdowns/api/DropDownListProps/#toc-popupsettings). 

**To Reproduce**
1. Open [this StackBlitz example](https://stackblitz.com/edit/u6b1pk?file=src/main.vue)
2. Expand the DropDownList

**Expected behavior**
We should be able to add a **className** to the component's popup and control the element to which the popup will be appended to.

**Comment by markglattback** [comment] 2022-06-16 14:02
I stumbled on a potential workaround today; setting `popupSettings.popupClass` adds a class to the first child of the popup, but not the popup root. This isn't documented anywhere or part of the `DropDownListProps` interface, however it is documented in the equivalent DatePicker which lead me to try it.

**Comment by zdravkov** [comment] 2022-08-12 13:33
Thank you for commenting on the issue - we are adding it in the planning for the upcoming product increment. Please excuse us for the inconvenience caused by it once again.

**Comment by zdravkov** [comment] 2022-09-02 10:50
Fixed with version 3.5.2 of Kendo Ui for Vue - https://stackblitz.com/edit/u6b1pk-7vi6km?file=src%2Fmain.vue,package.json

**Closed by zdravkov** 2022-09-02 10:50 UTC
Labels: bug, FP: In Development, SEV: Low
