### ISSUE TITLE
[Bug][Rating] Wrong import for utils/index

### ISSUE THREAD

**Issue by kdikov82** [telerik/kendo-vue#578] opened 2024-05-24 16:23 UTC
**Describe the bug**

Within Rating.tsx there is import from "./utils", but there is no such file and it should be "./utils/index":
import {
    calcIsFirstHalf,
    getRemainder,
    isHalf,
    isSelected,
    toRound
} from './utils';

The above throws "module not found error":
https://stackblitz.com/edit/vitest-dev-vitest-waqfpv?file=package.json

**Version**
5.0.2

**Comment by zdravkov** [comment] 2024-05-29 07:59
The issue is fixed in the 'dev' version of Kendo UI for Vue and will be included in the next official version.

**Closed by zdravkov** 2024-05-29 07:59 UTC
Labels: Bug, SEV: Critical, Kendo UI for Vue
