### ISSUE TITLE
Grid displays extra whitespace when scrolling to the bottom if grid is narrower than its columns when using virtual scroll

### ISSUE THREAD

**Issue by mmjsd** [telerik/kendo-vue#20] opened 2019-04-16 14:12 UTC
## I'm submitting a...
* Bug report

## Current behavior
When scrolling to the bottom of a grid where the columns are wider than the grid container, extra whitespace appears below the grid rows and the scrollbar may behave strangely.

## Expected behavior
No whitespace appears below the rows and scrolling behaves as normal.

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/fcsuzv?file=index.js

Scroll to the bottom of the list.

## What is the motivation or use case for changing the behavior?
The user experience when working with the grid is negatively impacted.

## Environment

Browser:
- Chrome (desktop) version 73

System:
- Platform:  Mac, Windows

**Comment by Dimitar-Goshev** [comment] 2020-07-08 10:42
The issue is not reproducible anymore. It seems fixed by the latest kendo themes, as the stackblitz references the latest version.

**Closed by Dimitar-Goshev** 2020-07-08 10:42 UTC
Labels: bug
