### ISSUE TITLE
DateRangePicker does not allow computed value for range value

### ISSUE THREAD

**Issue by SaphuA** [telerik/kendo-vue#2] opened 2019-01-24 13:51 UTC
## I'm submitting a...
* Bug report

## Current behavior
A wrapper element is added when the values of the component are changed by a computed value.

## Expected behavior
No wrapper element is added.

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/fxhflu?file=index.html
Just click the change button a couple of times.

**Comment by zdravkov** [comment] 2019-01-25 09:45
Hi @SaphuA 

Thank you for reporting the issue.

The issue is observed because of this bug in Kendo DateRangePicker widget - https://github.com/telerik/kendo-ui-core/issues/4793. Since it is not an issue in the Vue Wrappers I am closing this issue and you can follow the one that I linked.

Greetings,
Plamen

**Closed by zdravkov** 2019-01-25 09:45 UTC
