### ISSUE TITLE
The Switch Wrapper component doesn't work in a scenario with iPad which has connected mouse

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-vue#165] opened 2021-11-02 15:26 UTC
In a scenario when a mouse is connected to an iPad, using the mouse, we cannot switch the states of the Switch component. 
If the screen is touched, the Switch is correctly switching position. 

Here is a video demonstrating the issue:
[kendoswitch-rpreplay-final1635815724-mp4.zip](https://github.com/telerik/kendo-vue/files/7461935/kendoswitch-rpreplay-final1635815724-mp4.zip)

**Comment by zdravkov** [comment] 2022-02-09 09:17
With the latest Kendo UI for Vue release we introduced a [native Switch component](https://www.telerik.com/kendo-vue-ui/components/inputs/switch/) where the issue is not observed. Closing this one since it is rather an issue in the wrapper Kendo jQuery widget.

**Closed by zdravkov** 2022-02-09 09:17 UTC
Labels: bug, FP: Won't fix, SEV: High, wrappers
