### ISSUE TITLE
License validation problem when testing the Native Vue components version 3.5.1

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-vue#287] opened 2022-09-02 06:55 UTC
**Describe the bug**
The unit tests of a custom avatar component, which uses a Kendo UI for Vue Native Avatar are failing due to a problem with the license validation. This issue happens after upgrading the Kendo UI for Vue components from 3.5.0 to 3.5.1.

**To Reproduce**
1. Download [this project](https://github.com/telerik/kendo-vue/files/9475591/tests_failing_example-tar-gz.zip) and extract it
2. Run "yarn"
3. Run "yarn test"

**Expected behavior**
The tests should run correctly in version 3.5.0 as they used to be with version 3.5.1

**Screenshots**
![image](https://user-images.githubusercontent.com/41293735/188076475-0850cfe4-df6e-41f5-8c82-3eb8d229a3d5.png)

**Comment by zdravkov** [comment] 2022-09-02 10:46
The issue is fixed in version 3.5.2 of Kendo Ui for Vue

**Closed by zdravkov** 2022-09-02 10:46 UTC
Labels: bug, FP: In Development, SEV: Medium
