### ISSUE TITLE
[Bug][TreeList] Setting the rowClass function does not add the class name to the TR element

### ISSUE THREAD

**Issue by kdikov82** [telerik/kendo-vue#516] opened 2024-02-06 21:33 UTC
**Describe the bug**
We have a rowClass property for the TreeList that accepts a function, but currently it does not set the string value to the existing class names of the TR element

**To Reproduce**
In the following example, the custom string returned from the rowClass is not added to the TR element:
https://stackblitz.com/edit/bon9dn?file=src%2Fmain.vue

In the rendering of the TreeListRow we are missing the logic for adding the custom class name:

```
class={this.wrapperClass}
...
      wrapperClass(this: TreeListRowAll) {
        const { isSelected, isAltRow } = this.$props;
        return {
          'k-table-row': true,
          'k-table-alt-row': isAltRow,
          'k-master-row': true,
          'k-selected': isSelected,
          'k-alt': isAltRow,
          'k-group-footer': this.dataItem && this.dataItem.footer
        };
```

**Expected behavior**
The class name should be added to the default class names for the TR

**Browser**
Version 4.3.0

**Comment by zdravkov** [comment] 2024-02-20 14:34
The issue is fixed in v4.3.1 of Kendo UI for Vue: https://stackblitz.com/edit/bon9dn-y4kjev?file=src%2Fmain.vue

**Closed by zdravkov** 2024-02-20 14:34 UTC
Labels: Bug, SEV: High, Kendo UI for Vue
